TriggerRegister.registerCommand("planckeViewShortcuts").setCommandName("plancke");
function planckeViewShortcuts(shortcuts) {
  if (shortcuts === undefined) {
    return;
  }
  else if (shortcuts != undefined) {
      new Message(
          "&6&m" , ChatLib.getChatBreak("-") , "\n",
          "\n",
          ChatLib.getCenteredText("&c&lTHESE COMMANDS ARE CaSe-SenSiTivE!"),
        "&6&m" , ChatLib.getChatBreak("-") , "\n",
        "\n",
          new TextComponent("&c/bw <NAME>").setHoverValue("Will open up the Bedwars stats of the player entered"),
          "\n",
          new TextComponent("&c/sw <NAME>").setHoverValue("Will open up the Skywars stats of the player entered"),
          "\n",
          new TextComponent("&c/bb <NAME>").setHoverValue("Will open up the BuildBattle stats of the player entered"),
          "\n",
          new TextComponent("&c/arcade <NAME>").setHoverValue("Will open up the Arcade stats of the player entered"),
          "\n",
          new TextComponent("&c/bsg <NAME>").setHoverValue("Will open up the HungerGames or Blitz Survival Games stats of the player entered"),
          "\n",
          new TextComponent("&c/cac <NAME>").setHoverValue("Will open up the Cops And Crims stats of the player entered"),
          "\n",
          new TextComponent("&c/cc <NAME>").setHoverValue("Will open up the Crazy Walls stats of the player entered"),
          "\n",
          new TextComponent("&c/mw <NAME>").setHoverValue("Will open up the Mega Walls stats of the player entered"),
          "\n",
          new TextComponent("&c/mm <NAME>").setHoverValue("Will open up the Murder Mystery stats of the player entered"),
          "\n",
          new TextComponent("&c/sc <NAME>").setHoverValue("Will open up the Sky Clash stats of the player entered"),
          "\n",
          new TextComponent("&c/sh <NAME>").setHoverValue("Will open up the Super Smash stats of the player entered"),
          "\n",
          new TextComponent("&c/suhc <NAME>").setHoverValue("Will open up the SpeedUHC stats of the player entered"),
          "\n",
          new TextComponent("&c/tntgames <NAME>").setHoverValue("Will open up the TNTGames stats of the player entered"),
          "\n",
          new TextComponent("&c/uhc <NAME>").setHoverValue("Will open up the UHC stats of the player entered"),
          "\n",
          new TextComponent("&c/wl <NAME>").setHoverValue("Will open up the Warlords stats of the player entered"),
          "\n",
          new TextComponent("&c/ab <NAME>").setHoverValue("Will open up the Arena Brawl stats of the player entered"),
          "\n",
          new TextComponent("&c/pb <NAME>").setHoverValue("Will open up the Paintball stats of the player entered"),
          "\n",
          new TextComponent("&c/quake <NAME>").setHoverValue("Will open up the Quake stats of the player entered"),
          "\n",
          new TextComponent("&c/tkr <NAME>").setHoverValue("Will open up the Turbo Kart Racers stats of the player entered"),
          "\n",
          new TextComponent("&c/walls <NAME>").setHoverValue("Will open up the Walls stats of the player entered"),
          "\n",
          new TextComponent("&c/vampirez <NAME>").setHoverValue("Will open up the VampireZ stats of the player entered"),
          "\n",
          "\n",
          "&6&m" , ChatLib.getChatBreak("-") , "\n",
          "\n",
          ChatLib.getCenteredText("&c&lTHESE COMMANDS ARE CaSe-SenSiTivE!"),
          "\n",
          ChatLib.getCenteredText("&fHint: Hover over a command"),
        "&6&m" , ChatLib.getChatBreak("-") , "\n"
      ).chat();
  }
}
